amigo/admin_analytics_service/urls.py
from django.urls import path
from . import views

app_name = "admin_analytics_service"


urlpatterns = [
    path("", views.index, name="homepage"),
    path("register/", views.register_request, name="register"),
    path("register_logist/", views.register_logist_request, name="register_logist"),
    path('order-list', views.OrderList, name='orderlist'),
    path('order-create', views.OrderCreate.as_view(), name='ordercreate'),
    path('order-update/<int:id>', views.OrderUpdate, name='orderupdate'),
    path('order-delete/<int:id>', views.OrderDelete, name='orderdelete'),
    path('order-detail/<int:pk>', views.OrderDetail.as_view(), name='orderdetail'),
    path('offer_create', views.OfferCreate.as_view(), name='offercreate'),
    path('user_data/', views.user_data),

]

amigo/amigo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('client', include('client_service.urls')),
    path('', include('admin_analytics_service.urls')),
    path("dashboard", include("home.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

amigo/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from . import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

amigo/admin_analytics_service/models.py
from django.contrib.auth.models import User
from django.db import models

ORDER_STATUS_CHOICES = (
    ('OrderEvent', 'OrderEvent'),
    ('OrderCancelEvent', 'OrderCancelEvent'),
    ('OrderFreightReceiveEvent', 'OrderFreightReceiveEvent'),
    ('OrderFulfillmentEvent', 'OrderFulfillmentEvent'),
    ('OrderFailEvent', 'OrderFailEvent'),
)

OFFER_CHOICES = (
    ('OfferEvent', 'OfferEvent'),
    ('OfferAcceptEvent', 'OfferAcceptEvent'),
)


class Location(models.Model):
    location_id = models.IntegerField()
    name = models.CharField(max_length=255)
    coordinateX = models.FloatField()
    coordinateY = models.FloatField()
    srid = models.CharField(max_length=255)

class Delivery_Company(models.Model):
    delivery_company_id = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        if self.name:
            return f'{self.name}'
        return f'{self.id}'

    def __repr__(self):
        if self.name:
            return f'{self.name}'
        return f'{self.id}'


class Order(models.Model):

    client = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    weightKG = models.FloatField(null=True, blank=True)
    expectingPriceTenge = models.FloatField(null=True, blank=True)
    expectingDeliveryDate = models.DateTimeField(null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True, auto_now=True)
    FromLocation = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='from_location_order', null=True, blank=True)
    ToLocation = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='to_location_order', null=True, blank=True)
    type = models.CharField(max_length=255, choices=ORDER_STATUS_CHOICES, null=True, blank=True)
    fail_reason = models.IntegerField(null=True, blank=True)
    cancel_reason = models.IntegerField(null=True, blank=True)

class Offer(models.Model):

    delivery_Company = models.ForeignKey(Delivery_Company, on_delete=models.CASCADE, null=True, blank=True)
    offeredPriceTenge = models.FloatField(null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='offers', null=True, blank=True)
    type = models.CharField(max_length=255, choices=OFFER_CHOICES, null=True, blank=True)

class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('buyer', 'buyer'),
        ('logist' , 'logist'),
    )

    user_type = models.CharField(max_length=255, choices=USER_TYPE_CHOICES)
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE, blank=True, null=True)
    delivery_company = models.OneToOneField(Delivery_Company, related_name='profile', on_delete=models.CASCADE, blank=True, null=True)

amigo/admin_analytics_service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.
from django.forms import ModelForm, widgets
from django.shortcuts import render, redirect

from .models import Order, Offer, Delivery_Company, UserProfile


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)

        profile = UserProfile(user=user, user_type='buyer')
        if commit:
            user.save()
            profile.save()
        return user


class NewUserLogistForm(UserCreationForm):
    delivery_company_name = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)

        deliv_comp = Delivery_Company(name = self.cleaned_data['delivery_company_name'])
        deliv_comp.save()
        profile = UserProfile(delivery_company = deliv_comp, user=user, user_type='logist')

        if commit:
            user.save()
            profile.save()
        return user



class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class DateInput(forms.DateInput):
    input_type = 'date'

class OfferCreateForm(ModelForm):
    user = forms.IntegerField(widget=forms.HiddenInput)
    order = forms.IntegerField(widget=forms.HiddenInput)


    class Meta:
        model = Offer
        fields = ('offeredPriceTenge',)



    def save(self, user=None, commit=True, *args, **kwargs):
        offer = super().save(commit=False, *args, **kwargs)
        offer.type = 'OfferEvent'
        delivery_company = User.objects.get(pk=int(self.cleaned_data['user'])).userprofile.delivery_company
        offer.delivery_Company = delivery_company
        offer.order = Order.objects.get(pk=self.cleaned_data['order'])



        if commit:
            offer.save()
        return offer



class OrderCreateForm(ModelForm):
    expectingDeliveryDate = forms.DateField(widget=DateInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Order
        fields = ('weightKG', 'expectingDeliveryDate',
                  'FromLocation', 'ToLocation')
        widgets = {
            'expectingDeliveryDate': forms.DateInput,
        }

    def save(self, user=None,  commit=True, *args, **kwargs):
        order = super().save(commit=False, *args, **kwargs)
        order.type = 'OrderEvent'

        # self.request = kwargs.pop("request")
        c = self.get_context()

        order.client = self.request.user
        if commit:
            order.save()
        return order

amigo/admin_analytics_service/views.py
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import F
from django.db.models.functions import ExtractYear
from django.http import JsonResponse
from django.shortcuts import  render, redirect
from django.views.generic import ListView, CreateView, DetailView

from .forms import NewUserForm, OrderForm, OrderCreateForm, OfferCreateForm, NewUserLogistForm
from django.contrib.auth import login
from django.contrib import messages

from .models import Order, Offer


def register_request(request):
	if request.user.is_authenticated:
		return redirect('/')

	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("/")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="create_user.html", context={"register_form":form})


def register_logist_request(request):
	if request.user.is_authenticated:
		return redirect('/')


	if request.method == "POST":
		form = NewUserLogistForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("/")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserLogistForm()
	return render (request=request, template_name="create_user_logist.html", context={"register_form":form})


def index(request):
	return render (request=request, template_name="index_main.html")

class OrderListView(ListView):
	model = Order
	template_name = 'orderlist.html'

def OrderList(request):
	orders = Order.objects.all()
	return render(request,"orderlist.html",{'object_list':orders})

# def OrderCreate(request):
# 	if request.method == "POST":
# 		form = OrderForm(request.POST)
# 		if form.is_valid():
# 			try:
# 				form.save()
# 				model = form.instance
# 				return redirect('orderlist')
# 			except:
# 				pass
# 	else:
# 		form = OrderForm()
# 	return render(request,'ordercreate.html',{'form':form})

class OfferCreate(CreateView):
	form_class = OfferCreateForm
	success_url = '/order-list'

	# def get_success_url(self):
	# 	order = self.get_context_data()['order']
	# 	return redirect(f'order-detail/{order}')


class OrderCreate(CreateView):
	model = Order
	template_name = 'ordercreate.html'
	form_class = OrderCreateForm
	success_url = '/order-list'

	def get_form_kwargs(self, *args, **kwargs):
		kwargs = super().get_form_kwargs(*args, **kwargs)
		# kwargs['request'] = self.request
		kwargs.update({'request':self.request})
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user
		context["user"] = user
		return context

class OrderDetail(DetailView):
	model = Order
	template_name = 'orderdetail.html'
	offer_create_form = OfferCreateForm

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user_pk = None
		if not self.request.user.is_anonymous: #and logist
			user_pk = self.request.user.pk

		context['offers'] = Offer.objects.filter(order=self.get_object().id)
		context['offer_create_form'] = self.offer_create_form(initial={'user':user_pk,
																	   'order': self.get_object().id})
		context['request'] = self.request
		# context['order'] =
		return context


def OrderUpdate(request, id):
	order = Order.objects.get(id=id)
	form = OrderForm(initial={'client': order.client.name,
							  'weightKG': order.weightKG,
							  'expectingPriceTenge': order.expectingPriceTenge,
							  'expectingDeliveryDate': order.expectingDeliveryDate})
	if request.method == "POST":
		form = OrderForm(request.POST, instance=order)
		if form.is_valid():
			try:
				form.save()
				model = form.instance
				return redirect('/orderlist')
			except Exception as e:
				pass
	return render(request,'orderupdate.html',{'form':form})

def OrderDelete(request, id):
	order = Order.objects.get(id=id)
	try:
		order.delete()
	except:
		pass
	return redirect('orderlist')


def user_data(request):
	user = User.objects.all().count()
	logist = User.objects.filter(userprofile__user_type='logist').count()
	buyer = User.objects.filter(userprofile__user_type='buyer').count()


	return JsonResponse({
		'user_count':user,
		'logist_count': logist,
		'buyer': buyer,
		'percent': buyer/user
	}, safe=False)

amigo/admin_analytics_service/templates/base.html
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    </head>
<body>
    {% block content %}
    {% endblock %}
</body>

</html>

amigo/admin_analytics_service/templates/create_user.html
{% extends "header.html" %} {% block content %} {% load crispy_forms_tags %}

<!--Register-->
<style>
    .container {
        margin-left: auto;
        margin-right: auto;
        position: relative;
        width: 700px;
    }
    
    form {
        background-color: rgba(255, 255, 255, 0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
        padding: 50px 35px;
    }
    
    input {
        display: block;
        height: 50px;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.07);
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 14px;
        font-weight: 300;
    }
    
     ::placeholder {
        color: #e5e5e5;
    }
    
    button {
        margin-top: 50px;
        width: 100%;
        background-color: #ffffff;
        color: #080710;
        padding: 15px 0;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
    }
    
    label {
        display: block;
        margin-top: 30px;
        font-size: 16px;
        font-weight: 500;
    }
</style>
<div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %} {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

amigo/admin_analytics_service/templates/create_user_logist.html
{% extends "header.html" %} {% block content %} {% load crispy_forms_tags %}

<!--Register-->
<style>
    .container {
        margin-left: auto;
        margin-right: auto;
        position: relative;
        width: 700px;
    }
    
    form {
        background-color: rgba(255, 255, 255, 0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
        padding: 50px 35px;
    }
    
    input {
        display: block;
        height: 50px;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.07);
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 14px;
        font-weight: 300;
    }
    
     ::placeholder {
        color: #e5e5e5;
    }
    
    button {
        margin-top: 50px;
        width: 100%;
        background-color: #ffffff;
        color: #080710;
        padding: 15px 0;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
    }
    
    label {
        display: block;
        margin-top: 30px;
        font-size: 16px;
        font-weight: 500;
    }
</style>
<div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %} {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

amigo/admin_analytics_service/templates/dashboard_with_pivot.html
<html lang="en">
<head>
  <meta charSet="UTF-8">
  <title>Dashboard with Flexmonster</title>
  <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
  <style>
    /* Charts Style  */

    .fm-charts-color-1 {
      fill: #ffa600 !important;
    }

    .fm-charts-color-2 {
      fill: #7eae26 !important;
    }

    .fm-charts-color-3 {
      fill: #00a45a !important;
    }

    .fm-charts-color-4 {
      fill: #df3800 !important;
    }

    .fm-charts-color-5 {
      fill: #e95800 !important;
    }

    .fm-charts-color-6 {
      fill: #ffa600 !important;
    }</style>
</head>
<body>
<div id="pivot-table-container" data-url="http://localhost:8000/dashboard/data"></div>
<div id="pivot-chart-container"></div>
<script>
  function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
  }

  $.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function (data) {
      new Flexmonster({
        container: "#pivot-table-container",
        componentFolder: "https://cdn.flexmonster.com/",
        width: "100%",
        height: 430,
        toolbar: true,
        report: {
          dataSource: {
            type: "json",
            data: processData(data),
            mapping: {
              "product_category": {
                "caption": "Product Category"
              },
              "payment_method": {
                "caption": "Payment Method"
              },
              "shipping_cost": {
                "caption": "Shipping Cost",
                "type": "number"
              },
              "unit_price": {
                "caption": "Unit Price",
                "type": "number"
              }
            }
          },
          "slice": {
            "rows": [{
              "uniqueName": "product_category"
            }],
            "columns": [{
              "uniqueName": "payment_method"
            },
              {
                "uniqueName": "[Measures]"
              }
            ],
            "measures": [{
              "uniqueName": "shipping_cost",
              "aggregation": "sum"
            },
              {
                "uniqueName": "unit_price",
                "aggregation": "sum"
              }
            ]
          }
        }
      });
      new Flexmonster({
        container: "#pivot-chart-container",
        componentFolder: "https://cdn.flexmonster.com/",
        width: "100%",
        height: 430,
        //toolbar: true,
        report: {
          dataSource: {
            type: "json",
            data: processData(data),
            mapping: {
              "product_category": {
                "caption": "Product Category"
              },
              "payment_method": {
                "caption": "Payment Method"
              },
              "shipping_cost": {
                "caption": "Shipping Cost",
                "type": "number"
              },
              "unit_price": {
                "caption": "Unit Price",
                "type": "number"
              }
            }
          },
          "slice": {
            "rows": [{
              "uniqueName": "product_category"
            }],
            "columns": [{
              "uniqueName": "[Measures]"
            }],
            "measures": [{
              "uniqueName": "Price",
              "formula": "sum(\"shipping_cost\") + sum(\"unit_price\")",
              "caption": "Price"
            }]
          },
          "options": {
            "viewType": "charts",
            "chart": {
              "type": "pie"
            }
          }
        }
      });
    }
  });


</script>
</body>
</html>

amigo/admin_analytics_service/templates/header.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <title>Title</title>
    <style type="text/css">
        .navbar-custom {
            padding: 0 24px;
            background-color: black;
            box-shadow: 0px 0px 35px 0px rgb(154 161 171 / 15%);
            min-height: 70px;
            position: fixed;
            left: 0px;
            top: 0;
            right: 0;
            z-index: 1001;
        }
        
        div {
            display: block;
        }
        
        body {
            margin: 0;
            font-family: "MuseoSansCyrl", sans-serif;
            font-size: 0.9rem;
            font-weight: 400;
            line-height: 1.5;
            color: #6c757d;
            text-align: left;
            background-color: #fafbfe;
        }
        
        *,
        *::before,
        *::after {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        
        html {
            font-family: sans-serif;
            line-height: 1.15;
            -webkit-text-size-adjust: 100%;
            -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
        }
        
        .logo {
            max-width: 260px;
            max-height: 60px;
        }
        
        .list {
            float: right;
            color: white;
            position: relative;
            z-index: 1;
        }
        
        .mb-0 {
            margin-bottom: 0 !important;
        }
        
        .nav-link {
            color: white;
            min-width: 32px;
            text-align: center;
            margin: 0 0px;
            position: relative;
        }
        
        a {
            /* Цвет обычной ссылки */
            text-decoration: none;
            /* Убираем подчеркивание у ссылок */
        }
        
        a:hover {
            color: #b80a7e;
            /* Цвет ссылки при наведении на нее курсора мыши */
            text-decoration: underline;
            /* Добавляем подчеркивание */
        }
        
        .right-link {
            float: right;
            line-height: 70px;
        }
    </style>
</head>

<body>
    <div class="navbar-custom">
        <a href="https://e-agrin.com/ru/"><img src="https://e-agrin.com/images/logo-white.svg" class="logo text-center"></a>
        <div class="list-link list topbar-dropdown">
            <div class="right-link"> <a class="nav-link" href="/">Home</a></div>
            <div class="right-link"> <a class="nav-link" href="/register">Register</a> |&nbsp;</div>
            <div class="right-link"> <a class="nav-link" href="/order-list">Order-list</a> |&nbsp;</div>
            <div class="right-link"> <a class="nav-link" href="/order-detail/1">Order-detail</a> |&nbsp;</div>
            <div class="right-link"><a class="nav-link" href="/dashboard">Dashboard</a> |&nbsp;</div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} {% block content %} {% endblock %}

</body>

</html>

amigo/admin_analytics_service/templates/ordercreate.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<style type="text/css">
    .card-body {
        margin-left: auto;
        margin-right: auto;
        position: relative;
        width: 700px;
    }
    
    form {
        background-color: rgba(255, 255, 255, 0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
        padding: 50px 35px;
    }
    
    label {
        display: block;
        margin-top: 30px;
        font-size: 16px;
        font-weight: 500;
    }
    
    input {
        display: block;
        height: 50px;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.07);
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 14px;
        font-weight: 300;
    }
    
    select {
        display: block;
        height: 50px;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.07);
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 14px;
        font-weight: 300;
    }
</style>
<div class="card-body">
    <h5>Create Order</h5>
    <form method="post">
        {% csrf_token %} {{form.as_p}}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>
{% endblock %}

amigo/admin_analytics_service/templates/orderlist.html
{% extends "base.html" %} {% block content %}
<div class="card-body">
    <h4>Order List</h4>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">client</th>
                <th scope="col">weight</th>
                <th scope="col">expectingPriceTenge</th>
                <th scope="col">expectingDeliveryDate</th>
                <th scope="col">date</th>
                <th scope="col">FromLocation</th>
                <th scope="col">ToLocation</th>
                <th scope="col">type/Status</th>
            </tr>
        </thead>
        <tbody>
            {% for order in object_list %}
            <tr>
                <td>{{ order.client.name }}</td>

                <td>
                    <a href="/order-detail/{{order.id}}">{{order.weightKG}}</a></td>

                <td>{{order.expectingPriceTenge}}</td>
                <td>{{order.expectingDeliveryDate}}</td>
                <td>{{order.date}}</td>
                <td>{{order.FromLocation}}</td>
                <td>{{order.ToLocation}}</td>
                <td>{{order.type}}</td>
                <td><a type="button" class="btn btn-warning" href="/book-update/{{ order.id }}">Update</a>
                    <a type="button" class="btn btn-danger" href="/book-delete/{{ order.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a type="button" class="btn btn-success" href="{%url 'admin_analytics_service:ordercreate' %}">Create</a>
</div>
{% endblock %}

amigo/admin_analytics_service/templates/orderupdate.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>Update Book</h4>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <a type="button" class="btn btn-danger" href="{%url 'book-list' %}">Cancel</a>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div>
{% endblock %}